tasks:
  - init: |
      find . -type d -exec chmod 777 {} \;
      docker-compose pull
      brew install hugo
    command: |
      docker-compose up

ports:
  - port: 4000
    name: Jekyll
    description: Jekyll autobuild instance.