tasks:
  - name: Jekyll
    init: |
      find jekyll -type d -exec chmod 777 {} \;
      docker-compose -f jekyll/docker-compose.yml pull
    command: docker-compose -f jekyll/docker-compose.yml up
    openMode: split-right
  - name: Hugo
    init: sudo apt-get update && sudo apt-get install -y hugo
    command: (cd hugo && hugo server)
    openMode: split-left

ports:
  - port: 4000
    name: Jekyll
  - port: 1313
    name: Hugo
