tasks:
  - init: |
      find jekyll -type d -exec chmod 777 {} \;
      docker-compose -f jekyll/docker-compose.yml pull
      brew install hugo
    command: |
      docker-compose -f jekyll/docker-compose.yml up

ports:
  - port: 4000
    name: Jekyll
    description: Jekyll autobuild instance.