title: Soupbowl
subtitle: Ramblings of a DevOps Nerd
author: soup-bowl
email: code@soupbowl.io
description: >-
  Personal blog for Casey - a back-end developer specialising in PHP, primarily for WordPress developments.
  Primarily a source of niche setup guides, cool Raspberry Pi builds, and general ranting.
baseurl: ""
url: "https://blog.soupbowl.io"
footnote: Hello from London.
permalink: /:year/:month/:title

include: ['_redirects']
exclude: ['.github', '.vscode', 'README.md', 'LICENSE', 'docker-compose.yml', 'Gemfile.lock', 'Gemfile']

theme: minima
minima:
  date_format: "%-d %B %Y"
header_pages:
  - blog/index.html
  - guides.html

sass:
  style: compressed

disqus:
  shortname: soup-bowl
  show_policy: true

soupy:
  css_version: 4
  socials:
    github:    https://github.com/soup-bowl
    gitlab:    https://gitlab.com/soup-bowl
    wordpress: https://profiles.wordpress.org/soupbowl
    google:    https://g.dev/soupbowl
    osgrid:    hop://hg.osgrid.org:80/Willowbourne/195/25/25
    discord:   https://discord.com/users/555374749019013141
    docker:    https://hub.docker.com/u/soupbowl

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  tags: 
    enabled: true
    permalink: '/tags/:tag'
    layouts: 
      - autopage_collection.html

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins:
  - jekyll-feed
  - jemoji
