title: Soupbowl
subtitle: Ramblings of a DevOps Nerd
author: soup-bowl
email: code@soupbowl.io
description: >-
  Personal blog for Casey - a back-end developer specialising in PHP, primarily for WordPress developments.
  Primarily a source of niche setup guides, cool Raspberry Pi builds, and general ranting.
baseurl: ""
url: "https://soupbowl.blog"
footnote: Hello from London.
permalink: /:year/:month/:title

include: ['_redirects']
exclude: ['.github', '.vscode', 'README.md', 'LICENSE', 'docker-compose.yml', 'Gemfile.lock', 'Gemfile']

theme: minima
minima:
  date_format: "%-d %B %Y"
header_pages:
  - blog/index.html
  - guides.html

sass:
  style: compressed

disqus:
  shortname: soup-bowl
  show_policy: true

soupy:
  css_version: 4
  socials:
    twitter:   https://twitter.com/TheAlmightyWord
    mastodon:  https://mstdn.social/@soupbowl
    instagram: https://instagram.com/thealmightyword
    github:    https://github.com/soup-bowl
    gitlab:    https://gitlab.com/soup-bowl
    wordpress: https://profiles.wordpress.org/soupbowl
    google:    https://g.dev/soupbowl
    lastfm:    https://last.fm/user/soup-bowl
    osgrid:    hop://osgrid.org:80/soupbowl/128/128/30

paginate: 5
paginate_path: "/blog/page/:num/"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins:
  - jekyll-feed
  - jemoji
