title: Soupbowl
subtitle: Ramblings of a DevOps Nerd
author: soup-bowl
email: code@soupbowl.io
description: >-
  Personal blog for Casey - a back-end developer specialising in PHP, primarily for WordPress developments.
  Primarily a source of niche setup guides, cool Raspberry Pi builds, and general ranting.
baseurl: ""
url: "https://soupbowl.io"
footnote: Hello from London.
permalink: /:year/:month/:title:output_ext

include: ['_redirects']
exclude: ['.github', 'README.md', 'LICENSE', 'docker-compose.yml', 'Gemfile.lock', 'Gemfile']

theme: minima
minima:
  date_format: "%-d %B %Y"
header_pages:
  - projects/index.md
  - blog/index.html
  - guides.html

sass:
  style: compressed

disqus:
  shortname: soup-bowl
  show_policy: true

soupy:
  css_version: 2
  socials:
    twitter: https://twitter.com/TheAlmightyWord
    instagram: https://www.instagram.com/thealmightyword/
    github: https://github.com/soup-bowl
    gitlab: https://gitlab.com/soup-bowl
    wordpress: https://profiles.wordpress.org/soupbowl
    google: https://g.dev/soupbowl
    lastfm: https://www.last.fm/user/soup-bowl

paginate: 5
paginate_path: "/blog/page/:num/"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins:
  - jekyll-feed
  - jemoji
